import java.io.PrintWriter;
import java.net.Socket;
import java.util.Scanner;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author silve
 */
public class CadastraResposta extends javax.swing.JFrame {

    Scanner in;
    PrintWriter out;
    private String login1;
    private int question1;
    private int questao1;
    private int qtd1;
    //Connection conexao = trabalho.MinhaConexao.getInstance().sqlConnection;
    JFrame father;

    /**
     * Creates new form CadastraResposta
     */
    public CadastraResposta() {
        initComponents();
        question1 = 0;
        login1 = "";
        questao1 = 0;
    }

    public CadastraResposta(JFrame father) {
        initComponents();
        this.father = father;
        question1 = 0;
        login1 = "";
        questao1 = 0;

// TODO add your handling code here:
    }

    public CadastraResposta(String login, int question, int questao, int qtd) {
        initComponents();
        question1 = question;
        login1 = login;
        questao1 = questao;
        qtd1 = qtd;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NumAsser = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAssert = new javax.swing.JTextPane();
        btnCadastraResposta = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Plataforma do Professor");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NumAsser.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        getContentPane().add(NumAsser, new org.netbeans.lib.awtextra.AbsoluteConstraints(744, 107, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setText("Insira a resposta da questão");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Insira a resposta :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 215, -1, 32));

        jScrollPane1.setViewportView(txtAssert);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 223, 470, -1));

        btnCadastraResposta.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnCadastraResposta.setText("Cadastrar Resposta");
        btnCadastraResposta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastraRespostaActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastraResposta, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 300, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/7335.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, -40, 1280, 520));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastraRespostaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastraRespostaActionPerformed
        String resp = txtAssert.getText();
        if (txtAssert.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Nenhum campo pode estar em branco.", "Erro ao efetuar o Cadastro!", JOptionPane.ERROR_MESSAGE);
            txtAssert.setText("");
        } else {
            try {
                Socket socket = new Socket("192.168.91.60", 59001); //INFOS DO SERVIDOR
                in = new Scanner(socket.getInputStream());
                out = new PrintWriter(socket.getOutputStream(), true);

                int cond = 0;
                out.println("CADASTRAR_RESPOSTA " + resp + "‰" + questao1);

                while (!out.equals("")) {
                    cond = 1;
                    String input = in.nextLine();

                    if (input.equals("RESPOSTA_CADASTRADA")) {
                        this.setVisible(false);
                        DecideQuestion mc = new DecideQuestion(login1, question1, qtd1);
                        mc.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
                        mc.setVisible(true);
                        socket.close();
                    } else {
                        JOptionPane.showMessageDialog(null, "Erro ao registrar a resposta!", "Erro ao efetuar o Cadastro!", JOptionPane.ERROR_MESSAGE);
                        txtAssert.setText("");
                    }
                }
                if (cond == 0) {
                    JOptionPane.showMessageDialog(null, "Nenhum campo pode estar em branco.", "Erro ao efetuar o Cadastro!", JOptionPane.ERROR_MESSAGE);
                    txtAssert.setText("");
                }
                socket.close();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnCadastraRespostaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastraResposta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastraResposta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastraResposta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastraResposta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastraResposta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NumAsser;
    private javax.swing.JButton btnCadastraResposta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane txtAssert;
    // End of variables declaration//GEN-END:variables
}
