import java.io.IOException;
import java.io.PrintWriter;
import java.net.Socket;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

public class OverAluno2 extends javax.swing.JFrame {

    Scanner in;
    PrintWriter out;
    String loginn;
    JFrame father;

    /**
     * Creates new form OverAluno2
     */
    public OverAluno2() {
        initComponents();
    }

    OverAluno2(String loginn1) {
        initComponents();
        loginn = loginn1;
    }

    public OverAluno2(JFrame father) {
        initComponents();
        this.father = father;
// TODO add your handling code here:
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        sel2 = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        sel1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Plataforma do Aluno");
        setPreferredSize(new java.awt.Dimension(960, 700));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        jLabel13.setText("Insira a sub-matéria da pergunta :");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 330, 32));

        sel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        sel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sel2ActionPerformed(evt);
            }
        });
        getContentPane().add(sel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 350, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        jLabel12.setText("Insira a matéria :");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, -1, 32));

        sel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        sel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ArrayList<String> strList = new ArrayList<String>();//MATERIA
        try {
            Socket socket = new Socket("192.168.91.60", 59001); //INFOS DO SERVIDOR
            in = new Scanner(socket.getInputStream());
            out = new PrintWriter(socket.getOutputStream(), true);

            int cond = 0;
            out.println("SELETOR_MATERIA");
            strList.add("Selecionar Outro");
            while (!out.equals("")) {

                cond = 1;
                String input = in.nextLine();

                if (input.substring(0, 11).equals("MATERIAS_OK")) {

                    strList.add(input.substring(11));
                } else {
                    DefaultComboBoxModel model1 = new DefaultComboBoxModel(strList.toArray());
                    sel1.setModel(model1);
                    break;
                }
            }
            if (cond == 0) {
                strList.add("Selecionar Outro");
                DefaultComboBoxModel model1 = new DefaultComboBoxModel(strList.toArray());
                sel1.setModel(model1);
                socket.close();
            }
            socket.close();
        } catch (IOException ex) {
            Logger.getLogger(CadastraQuestao.class.getName()).log(Level.SEVERE, null, ex);
        }
        sel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sel1ActionPerformed(evt);
            }
        });
        getContentPane().add(sel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        jLabel1.setText("Insira de qual tópico você deseja saber o seu desempenho :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, 100));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setText("Voltar");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 440, -1, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton2.setText("Ver desempenho");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 440, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Documents-(1).jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-130, -40, 1150, 810));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void sel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sel2ActionPerformed
        sel2.setSelectedItem(this);
    }//GEN-LAST:event_sel2ActionPerformed

    private void sel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sel1ActionPerformed
        sel1.setSelectedItem(this);
        ArrayList<String> strList1 = new ArrayList<String>();
        Object mat = sel1.getSelectedItem();

        try {
            Socket socket = new Socket("192.168.91.60", 59001); //INFOS DO SERVIDOR
            in = new Scanner(socket.getInputStream());
            out = new PrintWriter(socket.getOutputStream(), true);

            int cond = 0;
            out.println("SELETOR_TOPICOS" + mat);
            strList1.add("Selecionar Outro");
            while (!out.equals("")) {

                cond = 1;
                String input = in.nextLine();

                if (input.substring(0, 11).equals("MATERIAS_OK")) {

                    strList1.add(input.substring(11));
                } else {
                    DefaultComboBoxModel model2 = new DefaultComboBoxModel(strList1.toArray());
                    sel2.setModel(model2);
                    break;
                }
            }
            if (cond == 0) {
                strList1.add("Selecionar Outro");
                DefaultComboBoxModel model2 = new DefaultComboBoxModel(strList1.toArray());
                sel2.setModel(model2);
                socket.close();
            }
            socket.close();
        } catch (IOException ex) {
            Logger.getLogger(CadastraQuestao.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_sel1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        OverAluno0 mc = new OverAluno0(loginn);
        mc.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        mc.setVisible(true);                 // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Object materia = sel1.getSelectedItem();
        Object submateria = sel2.getSelectedItem();
        if (materia.equals("Selecionar Outro") || submateria.equals("Selecionar Outro")) {
            JOptionPane.showMessageDialog(null, "Selecione alguma materia e submateria.", "Erro ao selecionar!", JOptionPane.ERROR_MESSAGE);
        } else {
            this.setVisible(false);
            OverAluno3 mc = new OverAluno3(loginn, materia, submateria);
            mc.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
            mc.setVisible(true);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OverAluno2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OverAluno2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OverAluno2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OverAluno2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OverAluno2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox sel1;
    private javax.swing.JComboBox sel2;
    // End of variables declaration//GEN-END:variables
}
