import java.io.IOException;
import java.io.PrintWriter;
import java.net.Socket;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.WindowConstants;

public class OverAluno1 extends javax.swing.JFrame {

    Scanner in;
    PrintWriter out;
    String loginn;
    JFrame father;

    /**
     * Creates new form OverAluno1
     */
    public OverAluno1() {
        initComponents();
    }

    OverAluno1(String loginn1) {
        initComponents();
        loginn = loginn1;
        atualizaDados();
    }

    public OverAluno1(JFrame father) {
        initComponents();
        this.father = father;
    }
    DecimalFormat df = new DecimalFormat("#.00");

    public void atualizaDados() {
        ArrayList<Questoes> questao = new ArrayList();
        DefaultListModel listModel = new DefaultListModel();
        listModel.addElement("Desempenho do aluno " + loginn + "");
        listModel.addElement("Nome da materia ------- Porcentagem de acerto");
        listModel.addElement("\n");

        try {
            Socket socket = new Socket("192.168.91.60", 59001); //INFOS DO SERVIDOR
            in = new Scanner(socket.getInputStream());
            out = new PrintWriter(socket.getOutputStream(), true);

            out.println("OVERVIEW_MATERIA_ALUNO    " + loginn);

            while (!out.equals("")) {
                String input = in.nextLine();
                if (input.substring(0, 12).equals("OVER_MATERIA")) {

                    int primeira = input.indexOf("‰");//INDICE DA PRIMEIRA OCORRENCIA DO CH +
                    int segunda = input.indexOf("‰", primeira + 1);//INDICE DA SEGUNDA OCORRENCIA DO CH +

                    String materia = input.substring(12, primeira);
                    Integer questoes_certas = Integer.parseInt(input.substring(primeira + 1, segunda));
                    Integer questoes_feitas = Integer.parseInt(input.substring(segunda + 1));

                    questao.add(new Questoes(materia, questoes_certas, questoes_feitas));

                } else if (input.equals("NAO_RESPONDEU_AINDA")) {
                    listModel.addElement("Voce nao respondeu nenhuma questao ainda!");
                    break;
                } else {
                    break;
                }
            }
            socket.close();
        } catch (IOException ex) {
            Logger.getLogger(OverAluno1.class.getName()).log(Level.SEVERE, null, ex);
        }

        for (Questoes c : questao) {
            double p1 = (double) c.getQf();
            double p2 = (double) c.getQc();
            double p3 = (p2 / p1) * 100;
            if (p3 != 0) {
                listModel.addElement(new String(c.getMateria() + " ------- " + df.format(p3) + "%"));
            } else {
                listModel.addElement(new String(c.getMateria() + " ------- " + "0,00%"));
            }
        }
        listMat.setModel(listModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listMat = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Plataforma do Aluno");
        setPreferredSize(new java.awt.Dimension(1000, 700));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listMat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        listMat.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listMat);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 950, 270));

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 36)); // NOI18N
        jLabel1.setText("Resultado por Disciplina");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 58, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setText("Voltar");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 580, 100, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton2.setText("Ir para Desempenho por Tópico");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 530, 380, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Documents-(1).jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-80, -50, 1320, 840));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        OverAluno0 mc = new OverAluno0(loginn);
        mc.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        mc.setVisible(true);           // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
        OverAluno2 mc = new OverAluno2(loginn);
        mc.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        mc.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OverAluno1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OverAluno1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OverAluno1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OverAluno1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OverAluno1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList listMat;
    // End of variables declaration//GEN-END:variables
}
