import java.io.IOException;
import java.io.PrintWriter;
import java.net.Socket;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.WindowConstants;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author silve
 */
public class OverProf0 extends javax.swing.JFrame {

    Scanner in;
    PrintWriter out;
    String loginn;
    int quest;
    JFrame father;

    /**
     * Creates new form OverProf0
     */
    public OverProf0() {
        initComponents();
    }

    OverProf0(String login, int quest1) {
        initComponents();
        loginn = login;
        quest = quest1;
        atualizaDados();
    }

    int i = 0;
    DecimalFormat df = new DecimalFormat("#.00");

    public void atualizaDados() {

        ArrayList<Questoes> questao = new ArrayList();

        DefaultListModel listModel = new DefaultListModel();
        listModel.addElement("Desempenho dos alunos no questionario de pin " + quest + "");

        try {
            Socket socket = new Socket("192.168.91.60", 59001); //INFOS DO SERVIDOR
            in = new Scanner(socket.getInputStream());
            out = new PrintWriter(socket.getOutputStream(), true);

            out.println("OVERVIEW_PROFESSOR        " + quest);

            while (!out.equals("")) {
                String input = in.nextLine();
                if (input.substring(0, 11).equals("OVER_ALUNOS")) {

                    int primeira = input.indexOf("‰");//INDICE DA PRIMEIRA OCORRENCIA DO CH +
                    int segunda = input.indexOf("‰", primeira + 1);//INDICE DA SEGUNDA OCORRENCIA DO CH +

                    String dificuldade = input.substring(11, primeira);
                    int qf = Integer.parseInt(input.substring(primeira + 1, segunda));
                    int qc = Integer.parseInt(input.substring(segunda + 1));

                    questao.add(new Questoes(qc, qf, dificuldade));
                } else {
                    break;
                }
            }
            socket.close();
        } catch (IOException ex) {
            Logger.getLogger(OverProf0.class.getName()).log(Level.SEVERE, null, ex);
        }

        int n = 0;
        for (Questoes c : questao) {
            n += c.getQft();
        }

        if (n != 0) {
            listModel.addElement("Numero da questao ----- Nivel de dificuldade ----- Porcentagem de acerto");
            listModel.addElement("\n");
            int i = 0;
            for (Questoes c : questao) {
                double p1 = (double) c.getQft();
                double p2 = (double) c.getQct();
                double p3 = (p2 / p1) * 100;
                i++;
                if ((int) p3 != 0) {
                    listModel.addElement(new String("Questao " + i + "-----" + c.getDificuldade() + " ----- " + df.format(p3) + "%"));
                } else {
                    listModel.addElement(new String("Questao " + i + "-----" + c.getDificuldade() + " ----- " + "0.00%"));
                }
            }
        } else {
            listModel.addElement("\n");
            listModel.addElement("Nenhum aluno respondeu o questionario selecionado ainda!");
        }
        listMat.setModel(listModel);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listMat = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Plataforma do Professor");
        setPreferredSize(new java.awt.Dimension(1000, 700));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listMat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        listMat.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listMat);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 890, 220));

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 36)); // NOI18N
        jLabel1.setText("Resultado por Questão");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setText("Voltar");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 570, 110, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton2.setText("Procurar Outro Questionário");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 520, 340, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Documents-(1).jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-90, 0, 1090, 720));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        TelaProfessor1 mc = new TelaProfessor1(loginn);
        mc.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        mc.setVisible(true);           // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
        InsiraPinProf mc = new InsiraPinProf(loginn);
        mc.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        mc.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OverProf0.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OverProf0.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OverProf0.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OverProf0.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OverProf0().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList listMat;
    // End of variables declaration//GEN-END:variables
}
